### ISSUE TITLE
URL returned is not formatted correctly

### ISSUE THREAD

**Issue by justechn** [ArekSredzki/electron-release-server#130]
I am trying to implement the electron release server and for now I am using docker compose to run it on my local machine. 

here is my docker-compose.yml
```
version: '2'
services:
  web:
    build: .
    environment:
      APP_USERNAME: admin
      APP_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: releaseserver
      DB_NAME: releaseserver
      DB_PASSWORD: secret
      TOKEN_SECRET: change_me_in_production
      APP_URL: 'localhost:5000'
    depends_on:
      - db
    ports:
      - '5000:80'
    entrypoint: ./scripts/wait.sh db:5432 -- npm start
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: releaseserver
```

When I call the server endpoint `http://localhost:5000/update/osx_64/0.0.1` I get json back, but the url in the response is not correct

```
{
  "url": "localhost:/download/0.0.2/osx_64?filetype=zip",
  "name": "0.0.2",
  "notes": "",
  "pub_date": "2017-05-10T23:12:52.000Z"
}
```

you will notice that the port is missing. So i added some debug to VersionController.js

```
sails.log.debug('Version candidate accepted');
sails.log.debug('appUrl '+sails.config.appUrl);
sails.log.debug(sails.config.appUrl + '/download/' + latestVersion.name + '/' + latestVersion.assets[0].platform + '?filetype=zip');
sails.log.debug(url.resolve(
              sails.config.appUrl,
              '/download/' + latestVersion.name + '/' +
              latestVersion.assets[0].platform + '?filetype=zip'
            ));
```

and what I get back in the debug is
```
web_1  | debug: Version candidate accepted
web_1  | debug: appUrl localhost:5000
web_1  | debug: localhost:5000/download/0.0.2/osx_64?filetype=zip
web_1  | debug: localhost:/download/0.0.2/osx_64?filetype=zip
```

it looks like url.resolve() is removing the port. Is there any way to fix this?
