### ISSUE TITLE
 I was able to get it to launch in docker, it wasn't direct

### ISSUE THREAD

**Issue by cisasmendi** [ArekSredzki/electron-release-server#299]
I was able to make it boot into docker-compose by making modifications. Remember to edit the values ​​between `<>`.I hope this helps someone
 - First create a directory and add `docker-compose.yml` that hosts the databases has to be yes or yes `posgresdb 10`. and start `docker-compose up -d`
``` 
version: '3'
services:
  db_pghacienda:                                 
    image: postgres:10-alpine              
    volumes:
      - ./postgresdb:/var/lib/postgresql  
    ports:
      - "<portdb>:5432"                    
    environment:                     
      POSTGRES_USER: <userdb>             
      POSTGRES_PASSWORD: <passdb>
      POSTGRES_DB: postgres
    restart: always
```
- Second, login with pgadmin (I have it installed in another docker-compose, or the container can be entered) and create the user and databases:
```
CREATE ROLE electron_release_server_user ENCRYPTED PASSWORD '<PASSWORD>' LOGIN;
CREATE DATABASE electron_release_server OWNER "electron_release_server_user";
CREATE DATABASE electron_release_server_sessions OWNER "electron_release_server_user";
```
- Third, download the project and modify it in line 47 of the `/config/docker.js` file: `process.env['DB_NAME']` by: `process.env['DB_NAME_SECTION']`
- Fourth, edit the `docker-compose.yml` file in the root directory like this (run `docker-compose up -d`):

```
version: '2'
services:
  web:
    build: .
    environment:
      APP_USERNAME: <usernameapp>
      APP_PASSWORD: <passwordapp>
      DB_HOST: <hostdb>
      DB_PORT: <portdb>
      DB_USERNAME: electron_release_server_user
      DB_NAME: electron_release_server  
      DB_NAME_SECCION: electron_release_server_seccions 
      DB_PASSWORD: <passdb>
      #Generate using: https://www.grc.com/passwords.htm
      TOKEN_SECRET: <tokensecret>
      APP_URL: 'localhost:<portapp>'
      ASSETS_PATH: '/usr/src/electron-release-server/releases'
    ports:
      - '<portapp>:80'
    entrypoint: ./scripts/wait.sh <hostdb>:<portdb> -- npm start
    volumes:
      - ./releases:/usr/src/electron-release-server/releases
 ```
